# Generated by Django 2.1.3 on 2018-11-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ManyToManyField(related_name='roles', to='crm.Role', verbose_name='角色列表'),
        ),
    ]
