# Generated by Django 2.1.3 on 2018-11-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20181108_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='菜单名称')),
                ('url_type', models.SmallIntegerField(choices=[(0, '绝对URL'), (1, '动态URL')], default=0, verbose_name='菜单类型')),
                ('url', models.CharField(max_length=200, verbose_name='URL地址')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('name', 'url')},
        ),
        migrations.AddField(
            model_name='role',
            name='menus',
            field=models.ManyToManyField(blank=True, to='crm.Menu', verbose_name='动态菜单'),
        ),
    ]
